### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by emmanpbarrameda** [RCyrix/open-admin-backup#1]
hello, how can i use this on my open-admin web system application?

 composer require open-admin-ext/open-admin-backup:dev-main

ERROR:
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires open-admin-ext/open-admin-backup, it could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by RCyrix** [comment]
![image](https://github.com/RCyrix/open-admin-backup/assets/124294361/f930fa8a-09e4-4c0a-9116-e49f56a0be02)

Please follow the installation instructions
